---

- name: Add a system user to run the build script
  user:
    generate_ssh_key: yes
    name: "{{ pkgbuilder_user }}"
    state: present
  become: true

- name: Prepare workspace for pkgbuilder
  file:
    path: "{{ pkgbuilder_base }}/{{ item }}"
    recurse: yes
    state: directory
    owner: "{{ pkgbuilder_user }}"
    group: "{{ pkgbuilder_user }}"
  with_items:
    - "{{ pkgbuilder_base }}"
    - "{{ pkgbuilder_home }}"
    - "{{ pkgbuilder_artifacts }}"
  become: yes

- name: Clone pkgbuilder repository
  git:
    repo: "{{ pkgbuilder_repository }}"
    dest: "{{ pkgbuilder_base }}/{{ pkgbuilder_home }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pkgbuilder_deps }}"
  become: true

- name: Copy host trusted.gpg.d
  command: cp -av /etc/apt/trusted.gpg.d "{{ pkgbuilder_base }}/{{ pkgbuilder_home }}"/apt
  register: output
  failed_when: output.rc != 0

- name: Install sudoers
  template:
    src: sudoer
    dest: /etc/sudoers.d/deepin_pbuilder
    mode: 0600
    validate: '/usr/sbin/visudo -cf %s'
  become: true

- name: Remove old script executables
  file:
    path: /usr/local/bin/deepin-buildpkg
    state: absent
  become: true

- name: Create symlinks for executables
  file:
    src: "{{ pkgbuilder_base }}/{{ pkgbuilder_home }}/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - cowimage
    - pkgbuilder
  become: true
...
